apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: grafanas.grafana.f110.dev
spec:
  group: grafana.f110.dev
  names:
    kind: Grafana
    listKind: GrafanaList
    plural: grafanas
    singular: grafana
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            description: APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values.
            type: string
          kind:
            description: Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated.
            type: string
          metadata:
            type: object
          spec:
            properties:
              adminUser:
                type: string
              apiVersion:
                type: string
              featureGates:
                items:
                  type: string
                type: array
              volumes:
                properties:
                  name:
                    type: string
                type: object
            type: object
          status:
            properties:
              observedGeneration:
                type: integer
            type: object
        type: object
    served: false
    storage: false
  - name: v1alpha2
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            description: APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values.
            type: string
          kind:
            description: Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated.
            type: string
          metadata:
            type: object
          spec:
            properties:
              adminUser:
                type: string
            type: object
          status:
            properties:
              observedGeneration:
                type: integer
            type: object
        type: object
    served: false
    storage: false
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: grafanausers.grafana.f110.dev
spec:
  group: grafana.f110.dev
  names:
    kind: GrafanaUser
    listKind: GrafanaUserList
    plural: grafanausers
    singular: grafanauser
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            description: APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values.
            type: string
          kind:
            description: Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated.
            type: string
          metadata:
            type: object
          spec:
            properties:
              admin:
                description: |2
                   admin indicates that the user has the privilege
                type: boolean
              email:
                type: string
            type: object
          status:
            properties:
              ready:
                type: boolean
            type: object
        type: object
    served: false
    storage: false
  - name: v1alpha2
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            description: APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values.
            type: string
          kind:
            description: Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated.
            type: string
          metadata:
            type: object
          spec:
            properties:
              admin:
                type: boolean
              email:
                type: string
            type: object
          status:
            properties:
              ready:
                type: boolean
            type: object
        type: object
    served: false
    storage: false
