apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: grafanas.grafana.f110.dev
spec:
  group: grafana.f110.dev
  names:
    kind: Grafana
    listKind: GrafanaList
    plural: grafanas
    singular: grafana
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            description: APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values.
            type: string
          kind:
            description: Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated.
            type: string
          metadata:
            type: object
          spec:
            properties:
              adminUser:
                type: string
              apiVersion:
                type: string
              featureGates:
                items:
                  type: string
                type: array
              userSelector:
                properties:
                  matchExpressions:
                    description: matchExpressions is a list of label selector requirements.
                      The requirements are ANDed.
                    items:
                      properties:
                        key:
                          description: key is the label key that the selector applies
                            to.
                          type: string
                        operator:
                          description: |-
                            operator represents a key's relationship to a set of values.
                             Valid operators are In, NotIn, Exists and DoesNotExist.
                          enum:
                          - In
                          - NotIn
                          - Exists
                          - DoesNotExist
                          type: string
                        values:
                          description: |-
                            values is an array of string values. If the operator is In or NotIn,
                             the values array must be non-empty. If the operator is Exists or DoesNotExist,
                             the values array must be empty. This array is replaced during a strategic
                             merge patch.
                          items:
                            type: string
                          type: array
                      required:
                      - key
                      - operator
                      - values
                      type: object
                    type: array
                  matchLabels:
                    additionalProperties:
                      type: string
                    description: |-
                      matchLabels is a map of {key,value} pairs. A single {key,value} in the matchLabels
                       map is equivalent to an element of matchExpressions, whose key field is "key", the
                       operator is "In", and the values array contains only "value". The requirements are ANDed.
                    type: object
                required:
                - matchLabels
                - matchExpressions
                type: object
              volumes:
                items:
                  properties:
                    name:
                      type: string
                  required:
                  - name
                  type: object
                type: array
            required:
            - apiVersion
            - featureGates
            - volumes
            - userSelector
            type: object
          status:
            properties:
              observedGeneration:
                format: int64
                type: integer
              observedTime:
                format: date-time
                type: string
              phase:
                enum:
                - Created
                - Creating
                type: string
            required:
            - observedGeneration
            - phase
            type: object
        type: object
    served: false
    storage: false
  - name: v1alpha2
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            description: APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values.
            type: string
          kind:
            description: Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated.
            type: string
          metadata:
            type: object
          spec:
            properties:
              adminUser:
                type: string
            type: object
          status:
            properties:
              history:
                description: history is a list of History
                items:
                  properties:
                    message:
                      description: message contains the result from the server
                      type: string
                  required:
                  - message
                  type: object
                type: array
              observedGeneration:
                format: int64
                type: integer
            required:
            - observedGeneration
            - history
            type: object
        type: object
    served: true
    storage: true
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: grafanausers.grafana.f110.dev
spec:
  group: grafana.f110.dev
  names:
    kind: GrafanaUser
    listKind: GrafanaUserList
    plural: grafanausers
    singular: grafanauser
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            description: APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values.
            type: string
          kind:
            description: Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated.
            type: string
          metadata:
            type: object
          spec:
            properties:
              admin:
                description: |-
                  admin indicates that the user has the privilege.
                   If admin is true, the user is an administrator.
                type: boolean
              email:
                type: string
            required:
            - email
            - admin
            type: object
          status:
            properties:
              ready:
                type: boolean
            required:
            - ready
            type: object
        type: object
    served: false
    storage: false
  - name: v1alpha2
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            description: APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values.
            type: string
          kind:
            description: Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated.
            type: string
          metadata:
            type: object
          spec:
            properties:
              admin:
                type: boolean
              email:
                type: string
            required:
            - email
            - admin
            type: object
          status:
            properties:
              ready:
                type: boolean
            required:
            - ready
            type: object
        type: object
    served: true
    storage: true
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: miniobuckets.minio.f110.dev
spec:
  group: minio.f110.dev
  names:
    kind: MinIOBucket
    listKind: MinIOBucketList
    plural: miniobuckets
    singular: miniobucket
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - description: Ready
      format: byte
      jsonPath: .status.ready
      name: ready
      type: string
    - description: age
      format: date
      jsonPath: .metadata.creationTimestamp
      name: age
      type: date
    name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            description: APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values.
            type: string
          kind:
            description: Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated.
            type: string
          metadata:
            type: object
          spec:
            properties:
              bucketFinalizePolicy:
                description: |-
                  bucket_finalize_policy is a policy when deleted CR Object.
                   If bucket_finalize_policy is an empty string, then it is the same as "keep".
                enum:
                - Delete
                - Keep
                type: string
              createIndexFile:
                description: create_index_file is a flag that creates index.html on
                  top of bucket.
                type: boolean
              maxBackups:
                type: integer
              policy:
                description: |-
                  policy is the policy of the bucket. One of public, readOnly, private.
                   If you don't want to give public access, set private or an empty value.
                   If it is an empty value, The bucket will not have any policy.
                   Currently, MinIOBucket can't use prefix based policy.
                enum:
                - Public
                - ReadOnly
                - Private
                type: string
              selector:
                properties:
                  matchExpressions:
                    description: matchExpressions is a list of label selector requirements.
                      The requirements are ANDed.
                    items:
                      properties:
                        key:
                          description: key is the label key that the selector applies
                            to.
                          type: string
                        operator:
                          description: |-
                            operator represents a key's relationship to a set of values.
                             Valid operators are In, NotIn, Exists and DoesNotExist.
                          enum:
                          - In
                          - NotIn
                          - Exists
                          - DoesNotExist
                          type: string
                        values:
                          description: |-
                            values is an array of string values. If the operator is In or NotIn,
                             the values array must be non-empty. If the operator is Exists or DoesNotExist,
                             the values array must be empty. This array is replaced during a strategic
                             merge patch.
                          items:
                            type: string
                          type: array
                      required:
                      - key
                      - operator
                      - values
                      type: object
                    type: array
                  matchLabels:
                    additionalProperties:
                      type: string
                    description: |-
                      matchLabels is a map of {key,value} pairs. A single {key,value} in the matchLabels
                       map is equivalent to an element of matchExpressions, whose key field is "key", the
                       operator is "In", and the values array contains only "value". The requirements are ANDed.
                    type: object
                required:
                - matchLabels
                - matchExpressions
                type: object
              serviceAccountJSON:
                properties:
                  key:
                    description: The key of the secret to select from.  Must be a
                      valid secret key.
                    type: string
                  name:
                    description: |-
                      Name of the referent.
                       More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                    type: string
                  optional:
                    description: Specify whether the Secret or its key must be defined
                    type: boolean
                required:
                - key
                type: object
            required:
            - selector
            - bucketFinalizePolicy
            - policy
            - createIndexFile
            - maxBackups
            type: object
          status:
            properties:
              ready:
                type: boolean
            required:
            - ready
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: miniousers.minio.f110.dev
spec:
  group: minio.f110.dev
  names:
    kind: MinIOUser
    listKind: MinIOUserList
    plural: miniousers
    singular: miniouser
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - description: Ready
      format: byte
      jsonPath: .status.ready
      name: ready
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            description: APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values.
            type: string
          kind:
            description: Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated.
            type: string
          metadata:
            type: object
          spec:
            properties:
              adminPasswordSecret:
                properties:
                  key:
                    description: The key of the secret to select from.  Must be a
                      valid secret key.
                    type: string
                  name:
                    description: |-
                      Name of the referent.
                       More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                    type: string
                  optional:
                    description: Specify whether the Secret or its key must be defined
                    type: boolean
                required:
                - key
                type: object
              mountPath:
                description: mount_path is a mount path of KV secrets engine.
                type: string
              path:
                description: path is a path in vault
                type: string
              selector:
                properties:
                  matchExpressions:
                    description: matchExpressions is a list of label selector requirements.
                      The requirements are ANDed.
                    items:
                      properties:
                        key:
                          description: key is the label key that the selector applies
                            to.
                          type: string
                        operator:
                          description: |-
                            operator represents a key's relationship to a set of values.
                             Valid operators are In, NotIn, Exists and DoesNotExist.
                          enum:
                          - In
                          - NotIn
                          - Exists
                          - DoesNotExist
                          type: string
                        values:
                          description: |-
                            values is an array of string values. If the operator is In or NotIn,
                             the values array must be non-empty. If the operator is Exists or DoesNotExist,
                             the values array must be empty. This array is replaced during a strategic
                             merge patch.
                          items:
                            type: string
                          type: array
                      required:
                      - key
                      - operator
                      - values
                      type: object
                    type: array
                  matchLabels:
                    additionalProperties:
                      type: string
                    description: |-
                      matchLabels is a map of {key,value} pairs. A single {key,value} in the matchLabels
                       map is equivalent to an element of matchExpressions, whose key field is "key", the
                       operator is "In", and the values array contains only "value". The requirements are ANDed.
                    type: object
                required:
                - matchLabels
                - matchExpressions
                type: object
              service:
                properties:
                  name:
                    description: |-
                      Name of the referent.
                       More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                    type: string
                type: object
              subGroups:
                description: sub_groups is a list of the name of group
                items:
                  type: string
                type: array
            required:
            - selector
            - path
            - mountPath
            - subGroups
            type: object
          status:
            properties:
              accessKey:
                type: string
              lastCommitId:
                format: int64
                type: integer
              ready:
                type: boolean
              vault:
                type: boolean
            required:
            - ready
            - accessKey
            - vault
            - lastCommitId
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
